### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dhhagan** [bsumlin/PyMieScatt#1]
Hey Ben,

Although there isn't a license text in the repository (something you may want to think about adding), I saw in the setup file you have this licensed under GPL. Is there a reason you decided to go with GPL rather than the much more liberal MIT license? I would love to explore using PyMieScatt within some of my other software packages, but GPL prevents that, since they are all going to be licensed MIT. Would love to hear your feedback on this topic.

**Comment by bsumlin** [comment]
Gimme a minute and I'll update this! Thanks for bringing this to my attention.

**Comment by kmuehlbauer** [comment]
Sorry for reviving this issue. In `setup.py` still mentions GPL.
