### ISSUE TITLE
ScatteringFunction q-space analysis

### ISSUE THREAD

**Issue by zcm73400** [bsumlin/PyMieScatt#12]
When using the ScatteringFunction to plot the q-space analysis for a spherical particle, the intensities return the same values as they do in theta space. I found this from doing the example on the docs page. I have only just begun working on this so I do not have insight on how to fix this.
![mietheory](https://user-images.githubusercontent.com/44439524/50858095-807be400-135d-11e9-8080-ab22514abb07.png)

**Comment by zcm73400** [comment]
In the master code, when using 'qspace', the angle measurement is designated as the log of the angle and then when q is calculated at the end of the function, it's being calculated based on that measurement. If you change line 310 to:
measure = np.linspace(minAngle, maxAngle, _steps)*np.pi/180

and you change the steps to increment by 1,

that will fix the issue and when you do the qspace analysis with the scattering function, you get the correct results.

I am new to git and not really knowledgeable about making a pull request if someone else can do that

**Comment by zcm73400** [comment]
I created the pull request

**Comment by bsumlin** [comment]
I don't know why this pull request never came to my inbox, but I'll work on this immediately!

**Comment by dvincentwest** [comment]
this issue seems to be still unfixed

**Comment by bsumlin** [comment]
Sorry that took so long. I made the adjustments and pushed 1.7.4. Give that a try.
