### ISSUE TITLE
Problem with Cratio returned by MieQ?

### ISSUE THREAD

**Issue by TalfanBarnie** [bsumlin/PyMieScatt#14]
Hi Benjamin,

Many thanks for making this great package available! It's a big help with my ash modelling work. One small question, currently Cratio returned by MieQ(...,asCrossSection=True) and Qratio returned by MieQ(...,asCrossSection=False) differ by a factor of cross sectional area - I notice you're multiplying by the area in mie.py line 55 - is this correct?

Sorry if I'm missing something!

Best wishes,

Talfan

**Comment by bsumlin** [comment]
Sorry it took so long to address this issue! You're absolutely correct. One too many copy/pastes. Fixed for forthcoming 1.8.1.
