### ISSUE TITLE
Values of backscatter efficiency is different

### ISSUE THREAD

**Issue by piyushether** [bsumlin/PyMieScatt#15]
Hi...
I am trying to compare the result of BHMie Fortran code with PyMieScatt using MieQ. I found that both provide similar values of the extinction and scattering efficiencies, but I found a difference in backscatter efficiency values of the order of 10. 
Please let me know about this difference in backscatter values.

**Comment by emlynjdavies** [comment]
Hi. I notice the case is closed. Can you say a bit more about what you found out?
