### ISSUE TITLE
Different result of Mie_Lognormal with different "numberOfBin"

### ISSUE THREAD

**Issue by AmberCrafter** [bsumlin/PyMieScatt#16]
HI, Benjamin
I have a problem when i used the Mie_Lognormal to simulation the scattering coefficient,
here is my data set and result:
I . Default setting of numberOfBin
simData = Mie_Lognormal(1.5+1E-7j,550,1.95,70,3000,lower=5,upper=60*1E3,returnDistribution=True,asDict=True)
and simData['Bsca']~57.7
II. Custom setting of numberOfBin = 20000
simData = Mie_Lognormal(1.5+1E-7j,550,1.95,70,3000,lower=5,upper=60*1E3,numberOfBin = 20000,returnDistribution=True,asDict=True)
and simData['Bsca']~115.5

Is it correct? On the other hand, I'm not sure whether can use np.trapz in np.logspace without setting "dx".

Best,
L.A.

**Comment by AmberCrafter** [comment]
def Mie_SD(m, wavelength, dp, ndp, nMedium=1.0, interpolate=False, asDict=False):
...
# trapz problem
  # Bext = trapz(Q_ext*aSDn)#,dp)
  # Bsca = trapz(Q_sca*aSDn)#,dp)
  # Babs = Bext-Bsca
  # Bback = trapz(Q_back*aSDn)#,dp)
  # Bratio = trapz(Q_ratio*aSDn)#,dp)
  # #bigG = trapz(g*Q_sca*aSDn,dp)/trapz(Q_sca*aSDn,dp)
  # bigG = trapz(g*Q_sca*aSDn)/trapz(Q_sca*aSDn)
  # Bpr = Bext - bigG*Bsca
# maybe correct code
  Bext = trapz(Q_ext*aSDn,dp)
  Bsca = trapz(Q_sca*aSDn,dp)
  Babs = Bext-Bsca
  Bback = trapz(Q_back*aSDn,dp)
  Bratio = trapz(Q_ratio*aSDn,dp)
  bigG = trapz(g*Q_sca*aSDn,dp)/trapz(Q_sca*aSDn,dp)
  # bigG = trapz(g*Q_sca*aSDn)/trapz(Q_sca*aSDn)
  Bpr = Bext - bigG*Bsca
...

Best,
L.A.

**Comment by bsumlin** [comment]
Sorry it took so long to resolve this issue, but it's fixed as of version 1.8.0. This problem arose as an attempt to resolve differences between laboratory data from instrumentation and theoretical data from analytical size distribution expressions. These data sources require different math to make sense of their outputs, but previously I had applied a single formulation to both sources. Go ahead and update and see if you still have issues.

**Comment by AmberCrafter** [comment]
thanks for your update!
