### ISSUE TITLE
PEP8 Compatability

### ISSUE THREAD

**Issue by dhhagan** [bsumlin/PyMieScatt#2]
Moving forward, it might be a good idea to follow the python style guide/conventions according to [PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions). This might be a bit of work (and something you may want to do), but I think it's worth thinking about/discussing. There are tools available to help guide through this process such as various linters as well as commercial products such as [codeclimate](https://codeclimate.com/).

Let me know if you'd like any help implementing these; I can certainly take a stab at it.

**Comment by bsumlin** [comment]
PEP8 compliance is underway!
