### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Prowess2014** [bsumlin/PyMieScatt#4]
C:\Windows\system32>pip install PyMieScatt

Collecting PyMieScatt
  Using cached PyMieScatt-1.4.2-py3-none-any.whl
Requirement already satisfied: matplotlib in c:\users\xxx\appdata\roaming\python\python36\site-packages (from PyMieScatt)
Requirement already satisfied: numpy in c:\users\xxx\appdata\roaming\python\python36\site-packages (from PyMieScatt)
Collecting shapely (from PyMieScatt)
  Using cached Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-_prs81qu\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-_prs81qu\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\program files\python\python36\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------

**Comment by ArminiusC** [comment]
"pip install PyMieScatt" does not work on my windows 7 machine either...

**Comment by Aretru** [comment]
Did somebody resolve this issue?

**Comment by bsumlin** [comment]
Please install Shapely from GitHub, the automatic install within PyMieScatt (or pip install Shapely) doesn't work. This is an issue with Shapely.
