### ISSUE TITLE
missing 'x'-parameter in 'scipy.integrate.trapz' - function

### ISSUE THREAD

**Issue by ArminiusC** [bsumlin/PyMieScatt#5]
when using the implemented trapezoidal rule from SciPy in line 223 and so on [here](https://github.com/bsumlin/PyMieScatt/blob/master/PyMieScatt/Mie.py) calculating the Mie coefficients, you have to give the scipy.integrate.trapz-function the 'x'-parameter (in this case the 'dp'-values), otherwise the spacing between all y-elements is dx = 1, which gives you unwanted results.

**Comment by bsumlin** [comment]
On it

**Comment by bsumlin** [comment]
I closed this issue long ago but forgot to close it on GitHub.
