### ISSUE TITLE
Version update on PYPI

### ISSUE THREAD

**Issue by kmuehlbauer** [bsumlin/PyMieScatt#6]
The latest version on PyPI is `1.7.1` (https://pypi.org/project/PyMieScatt/#history). The latest version in this repo is 1.7.3. Would be nice if PyPI can be updated and while doing so, please also have a look here: #1.

**Comment by kmuehlbauer** [comment]
@bsumlin If all license issues are sorted out, it would be great to release a new version which contains all these changes and upload to PyPI.

**Comment by kmuehlbauer** [comment]
@bsumlin Now that the licensing is fixed it would be great to release a new version and upload it to PyPI.

Then we can wait for the conda-bot to create a version update PR.

**Comment by kmuehlbauer** [comment]
BTW, your package is used for teaching students at the University of Bonn, Germany.

Keep up the good work. And I'm trying to help improving this PyMieScatt.

**Comment by kmuehlbauer** [comment]
Is this something which we can expect to happen in the near future? The current version on PyPI (1.7.1) lacks some fixes for Mie-Processing (see https://github.com/bsumlin/PyMieScatt/commit/36f06c5bc47769d1331371c07f5f51d2cdf7a7bb).

**Comment by bsumlin** [comment]
I swear I'd fixed that! Let me get a new version rolling, I'll update when it's complete. Thanks very much for your help! Can you tell me a little more about how PyMieScatt is being used for education? That's very exciting to hear!

**Comment by kmuehlbauer** [comment]
@bsumlin Great! Yes it's already fixed here, but the latest version wasn't uploaded to PyPI.

**Comment by vecoveco** [comment]
@bsumlin Hi! Yes we are using PyMieScatt for our remote sensing lecture since this semester. It is based on G. Petty and Bohren. The students have to calculate and analyze different parameters of a certain cloud (DSD, Q, Phasefunc, beta...etc) for their final thesis with PyMieScatt. These are then used for Monte Carlo simulation and Two Stream approximation. A big compliment to PyMieScatt!

**Comment by kmuehlbauer** [comment]
@bsumlin Sorry for nagging. When can we expect `1.7.3` at PyPI? The latest version there is `1.7.1`.

**Comment by bsumlin** [comment]
Whoops! Apparently some time ago I edited my PyPi update script to update one of my private repos of a completely unrelated project. I’ve been running it all this time wondering why PyMieScatt wasn’t updating. I’ve fixed it, 1.7.3 should be on PyPi now!

--
Ben

**Comment by kmuehlbauer** [comment]
Thanks @bsumlin!
