### ISSUE TITLE
Adding nMedium for MieQCoreShell

### ISSUE THREAD

**Issue by willmendil** [bsumlin/PyMieScatt#9]
Hi, 
I've been enjoying your implementation of Mie theory in python, but I couldn't help and notice you have not accounted for a change in the medium for the core shell calculation. Is there a particular reason? are you going to implement it?
Thanks 

**EDIT** : I took the liberty to propose a pull request with the modification of the coreshell calculation

**Comment by willmendil** [comment]
I took the liberty to propose a pull request with the modification of the coreshell calculation

**Comment by bsumlin** [comment]
Sorry it took so long to get to this issue, but I can address it now. There's nothing preventing the inclusion of nMedium in the core-shell functions, and I've done so, but I can't guarantee that the math is robust at this point...I'll need to think about it. I've added a warning to the code to inform the user whenever they specify a non-unity nMedium.
